# Generated by Django 5.1.1 on 2024-10-01 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.CharField(blank=True, choices=[('Zara', 'Zara'), ('H&M', 'H&M'), ('Gucci', 'Gucci'), ('Prada', 'Prada'), ('Versace', 'Versace'), ('Armani', 'Armani'), ('Louis Vuitton', 'Louis Vuitton'), ('Nike', 'Nike'), ('Adidas', 'Adidas'), ('Under Armour', 'Under Armour'), ('Ralph Lauren', 'Ralph Lauren'), ('Levis', 'Levis'), ('Calvin Klein', 'Calvin Klein'), ('Tommy Hilfiger', 'Tommy Hilfiger'), ('Burberry', 'Burberry'), ('Balenciaga', 'Balenciaga'), ('Dior', 'Dior'), ('Dolce & Gabbana', 'Dolce & Gabbana'), ('Gap', 'Gap'), ('Puma', 'Puma'), ('Timberland', 'Timberland'), ('Clarks', 'Clarks'), ('Vans', 'Vans'), ('Converse', 'Converse'), ('New Balance', 'New Balance'), ('Reebok', 'Reebok'), ('Dr. Martens', 'Dr. Martens')], max_length=100, null=True)),
                ('color', models.CharField(choices=[('blue', 'Blue'), ('red', 'Red'), ('yellow', 'Yellow'), ('white', 'White'), ('black', 'Black'), ('pink', 'Pink'), ('brown', 'Brown'), ('gray', 'Gray'), ('green', 'Green'), ('cyan', 'Cyan'), ('teal', 'Teal'), ('aqua', 'Aqua'), ('orange', 'Orange'), ('violet', 'Violet'), ('tan', 'Tan'), ('magenta', 'Magenta'), ('maroon', 'Maroon'), ('olive', 'Olive'), ('lime', 'Lime'), ('ruby', 'Ruby')], max_length=100)),
                ('price', models.FloatField()),
                ('gender', models.CharField(choices=[('female', 'Female'), ('male', 'Male')], max_length=20)),
                ('rating', models.DecimalField(blank=True, choices=[(0.0, '0'), (1.0, '1 Star'), (2.0, '2 Stars'), (3.0, '3 Stars'), (4.0, '4 Stars'), (5.0, '5 Stars')], decimal_places=1, max_digits=2, null=True)),
                ('by_count', models.IntegerField(default=0)),
                ('sale_count', models.IntegerField(default=0)),
                ('discount', models.FloatField(default=0)),
                ('season', models.CharField(choices=[('summer', 'Summer'), ('winter', 'Winter'), ('spring', 'Spring'), ('Autumn', 'Autumn')], max_length=100)),
                ('name', models.CharField(choices=[('Handbag', 'Handbag'), ('Shoulder Bag', 'Shoulder Bag'), ('Tote Bag', 'Tote Bag'), ('Backpack', 'Backpack'), ('Clutch', 'Clutch'), ('Crossbody Bag', 'Crossbody Bag'), ('Messenger Bag', 'Messenger Bag'), ('Weekend Bag', 'Weekend Bag'), ('Travel Bag', 'Travel Bag'), ('Laptop Bag', 'Laptop Bag'), ('Diaper Bag', 'Diaper Bag'), ('Fanny Pack', 'Fanny Pack'), ('Belt Bag', 'Belt Bag'), ('Bucket Bag', 'Bucket Bag'), ('Gym Bag', 'Gym Bag')], max_length=100)),
                ('image', models.ImageField(upload_to='bags_images/')),
                ('category', models.CharField(choices=[('bags', 'Bags'), ('designer_handbags', 'Designer Handbags'), ('purses', 'Purses'), ('shoulder_bags', 'Shoulder bags')], max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Dress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.CharField(blank=True, choices=[('Zara', 'Zara'), ('H&M', 'H&M'), ('Gucci', 'Gucci'), ('Prada', 'Prada'), ('Versace', 'Versace'), ('Armani', 'Armani'), ('Louis Vuitton', 'Louis Vuitton'), ('Nike', 'Nike'), ('Adidas', 'Adidas'), ('Under Armour', 'Under Armour'), ('Ralph Lauren', 'Ralph Lauren'), ('Levis', 'Levis'), ('Calvin Klein', 'Calvin Klein'), ('Tommy Hilfiger', 'Tommy Hilfiger'), ('Burberry', 'Burberry'), ('Balenciaga', 'Balenciaga'), ('Dior', 'Dior'), ('Dolce & Gabbana', 'Dolce & Gabbana'), ('Gap', 'Gap'), ('Puma', 'Puma'), ('Timberland', 'Timberland'), ('Clarks', 'Clarks'), ('Vans', 'Vans'), ('Converse', 'Converse'), ('New Balance', 'New Balance'), ('Reebok', 'Reebok'), ('Dr. Martens', 'Dr. Martens')], max_length=100, null=True)),
                ('color', models.CharField(choices=[('blue', 'Blue'), ('red', 'Red'), ('yellow', 'Yellow'), ('white', 'White'), ('black', 'Black'), ('pink', 'Pink'), ('brown', 'Brown'), ('gray', 'Gray'), ('green', 'Green'), ('cyan', 'Cyan'), ('teal', 'Teal'), ('aqua', 'Aqua'), ('orange', 'Orange'), ('violet', 'Violet'), ('tan', 'Tan'), ('magenta', 'Magenta'), ('maroon', 'Maroon'), ('olive', 'Olive'), ('lime', 'Lime'), ('ruby', 'Ruby')], max_length=100)),
                ('price', models.FloatField()),
                ('gender', models.CharField(choices=[('female', 'Female'), ('male', 'Male')], max_length=20)),
                ('rating', models.DecimalField(blank=True, choices=[(0.0, '0'), (1.0, '1 Star'), (2.0, '2 Stars'), (3.0, '3 Stars'), (4.0, '4 Stars'), (5.0, '5 Stars')], decimal_places=1, max_digits=2, null=True)),
                ('by_count', models.IntegerField(default=0)),
                ('sale_count', models.IntegerField(default=0)),
                ('discount', models.FloatField(default=0)),
                ('season', models.CharField(choices=[('summer', 'Summer'), ('winter', 'Winter'), ('spring', 'Spring'), ('Autumn', 'Autumn')], max_length=100)),
                ('category', models.CharField(blank=True, choices=[('Formal', 'Formal'), ('Casual', 'Casual'), ('Sportswear', 'Sportswear'), ('Business', 'Business'), ('Evening', 'Evening'), ('Traditional', 'Traditional')], max_length=100, null=True)),
                ('name', models.CharField(choices=[('A-Line Dress', 'A-Line dress'), ('Maxi Dress', 'Maxi dress'), ('Midi Dress', 'Midi dress'), ('Sheath Dress', 'Sheath dress'), ('Cocktail Dress', 'Cocktail Dress'), ('Shift Dress', 'Shift dress'), ('Wrap Dress', 'Wrap dress'), ('Tunic Dress', 'Tunic dress'), ('Ball Gown', 'Bola dress'), ('Peplum Dress', 'Peplum dress'), ('Empire Waist Dress', 'Empire Waist Dress'), ('Fit and Flare Dress', 'Fit and Flare Dress'), ('Bohemian Dress', 'Bohemia dress'), ('Pencil Dress', ' Pencil dress'), ('Sundress', 'Sundress dress'), ('Suit', 'Suit'), ('Blazer', 'Blazer'), ('Tuxedo', 'Tuxedo'), ('Dress Shirt', 'Dress Shirt'), ('Chinos', 'Chinos'), ('Cargo Pants', 'Cargo Pants'), ('Dress Pants', 'Dress Pants'), ('Linen Suit', 'Linen Suit'), ('Vest', 'Vest'), ('Overcoat', 'Overcoat'), ('Tailored Suit', 'Tailored Suit'), ('Smart Casual Outfit', 'Smart Casual Outfit'), ('Evening Wear', 'Evening Wear')], max_length=100)),
                ('size', models.CharField(choices=[('XXS', 'XXS'), ('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL'), ('XXXL', 'XXXL'), ('4XL', '4XL'), ('5XL', '5XL')], max_length=5)),
                ('image', models.ImageField(upload_to='dress_images/')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Electrical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('color', models.CharField(choices=[('blue', 'Blue'), ('red', 'Red'), ('yellow', 'Yellow'), ('white', 'White'), ('black', 'Black'), ('pink', 'Pink'), ('brown', 'Brown'), ('gray', 'Gray'), ('green', 'Green'), ('cyan', 'Cyan'), ('teal', 'Teal'), ('aqua', 'Aqua'), ('orange', 'Orange'), ('violet', 'Violet'), ('tan', 'Tan'), ('magenta', 'Magenta'), ('maroon', 'Maroon'), ('olive', 'Olive'), ('lime', 'Lime'), ('ruby', 'Ruby')], max_length=100)),
                ('price', models.FloatField()),
                ('gender', models.CharField(choices=[('female', 'Female'), ('male', 'Male')], max_length=20)),
                ('rating', models.DecimalField(blank=True, choices=[(0.0, '0'), (1.0, '1 Star'), (2.0, '2 Stars'), (3.0, '3 Stars'), (4.0, '4 Stars'), (5.0, '5 Stars')], decimal_places=1, max_digits=2, null=True)),
                ('by_count', models.IntegerField(default=0)),
                ('sale_count', models.IntegerField(default=0)),
                ('discount', models.FloatField(default=0)),
                ('season', models.CharField(choices=[('summer', 'Summer'), ('winter', 'Winter'), ('spring', 'Spring'), ('Autumn', 'Autumn')], max_length=100)),
                ('name', models.CharField(choices=[], max_length=100)),
                ('brand', models.CharField(choices=[], max_length=50)),
                ('image', models.ImageField(upload_to='electrical_images/')),
                ('category', models.CharField(choices=[], max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Jackets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('color', models.CharField(choices=[('blue', 'Blue'), ('red', 'Red'), ('yellow', 'Yellow'), ('white', 'White'), ('black', 'Black'), ('pink', 'Pink'), ('brown', 'Brown'), ('gray', 'Gray'), ('green', 'Green'), ('cyan', 'Cyan'), ('teal', 'Teal'), ('aqua', 'Aqua'), ('orange', 'Orange'), ('violet', 'Violet'), ('tan', 'Tan'), ('magenta', 'Magenta'), ('maroon', 'Maroon'), ('olive', 'Olive'), ('lime', 'Lime'), ('ruby', 'Ruby')], max_length=100)),
                ('price', models.FloatField()),
                ('gender', models.CharField(choices=[('female', 'Female'), ('male', 'Male')], max_length=20)),
                ('rating', models.DecimalField(blank=True, choices=[(0.0, '0'), (1.0, '1 Star'), (2.0, '2 Stars'), (3.0, '3 Stars'), (4.0, '4 Stars'), (5.0, '5 Stars')], decimal_places=1, max_digits=2, null=True)),
                ('by_count', models.IntegerField(default=0)),
                ('sale_count', models.IntegerField(default=0)),
                ('discount', models.FloatField(default=0)),
                ('season', models.CharField(choices=[('summer', 'Summer'), ('winter', 'Winter'), ('spring', 'Spring'), ('Autumn', 'Autumn')], max_length=100)),
                ('name', models.CharField(choices=[], max_length=100)),
                ('brand', models.CharField(blank=True, choices=[], max_length=50, null=True)),
                ('image', models.ImageField(upload_to='jackets_images/')),
                ('category', models.CharField(choices=[], max_length=255)),
                ('size', models.CharField(choices=[('XXS', 'XXS'), ('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL'), ('XXXL', 'XXXL'), ('4XL', '4XL'), ('5XL', '5XL')], max_length=5)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Jewelry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('color', models.CharField(choices=[('blue', 'Blue'), ('red', 'Red'), ('yellow', 'Yellow'), ('white', 'White'), ('black', 'Black'), ('pink', 'Pink'), ('brown', 'Brown'), ('gray', 'Gray'), ('green', 'Green'), ('cyan', 'Cyan'), ('teal', 'Teal'), ('aqua', 'Aqua'), ('orange', 'Orange'), ('violet', 'Violet'), ('tan', 'Tan'), ('magenta', 'Magenta'), ('maroon', 'Maroon'), ('olive', 'Olive'), ('lime', 'Lime'), ('ruby', 'Ruby')], max_length=100)),
                ('price', models.FloatField()),
                ('gender', models.CharField(choices=[('female', 'Female'), ('male', 'Male')], max_length=20)),
                ('rating', models.DecimalField(blank=True, choices=[(0.0, '0'), (1.0, '1 Star'), (2.0, '2 Stars'), (3.0, '3 Stars'), (4.0, '4 Stars'), (5.0, '5 Stars')], decimal_places=1, max_digits=2, null=True)),
                ('by_count', models.IntegerField(default=0)),
                ('sale_count', models.IntegerField(default=0)),
                ('discount', models.FloatField(default=0)),
                ('season', models.CharField(choices=[('summer', 'Summer'), ('winter', 'Winter'), ('spring', 'Spring'), ('Autumn', 'Autumn')], max_length=100)),
                ('name', models.CharField(choices=[], max_length=100)),
                ('image', models.ImageField(upload_to='jewelry_images/')),
                ('size', models.DecimalField(decimal_places=2, max_digits=5)),
                ('composition', models.DecimalField(decimal_places=2, default=None, max_digits=5)),
                ('brand', models.CharField(blank=True, choices=[('Tiffany & Co.', 'Tiffany & Co.'), ('Cartier', 'Cartier'), ('Bvlgari', 'Bvlgari'), ('Pandora', 'Pandora'), ('Swarovski', 'Swarovski')], max_length=100, null=True)),
                ('category', models.CharField(blank=True, choices=[('Necklace', 'Necklace'), ('Ring', 'Ring'), ('Bracelet', 'Bracelet'), ('Earrings', 'Earrings'), ('Watch', 'Watch')], max_length=100, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Shoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.CharField(blank=True, choices=[('Zara', 'Zara'), ('H&M', 'H&M'), ('Gucci', 'Gucci'), ('Prada', 'Prada'), ('Versace', 'Versace'), ('Armani', 'Armani'), ('Louis Vuitton', 'Louis Vuitton'), ('Nike', 'Nike'), ('Adidas', 'Adidas'), ('Under Armour', 'Under Armour'), ('Ralph Lauren', 'Ralph Lauren'), ('Levis', 'Levis'), ('Calvin Klein', 'Calvin Klein'), ('Tommy Hilfiger', 'Tommy Hilfiger'), ('Burberry', 'Burberry'), ('Balenciaga', 'Balenciaga'), ('Dior', 'Dior'), ('Dolce & Gabbana', 'Dolce & Gabbana'), ('Gap', 'Gap'), ('Puma', 'Puma'), ('Timberland', 'Timberland'), ('Clarks', 'Clarks'), ('Vans', 'Vans'), ('Converse', 'Converse'), ('New Balance', 'New Balance'), ('Reebok', 'Reebok'), ('Dr. Martens', 'Dr. Martens')], max_length=100, null=True)),
                ('color', models.CharField(choices=[('blue', 'Blue'), ('red', 'Red'), ('yellow', 'Yellow'), ('white', 'White'), ('black', 'Black'), ('pink', 'Pink'), ('brown', 'Brown'), ('gray', 'Gray'), ('green', 'Green'), ('cyan', 'Cyan'), ('teal', 'Teal'), ('aqua', 'Aqua'), ('orange', 'Orange'), ('violet', 'Violet'), ('tan', 'Tan'), ('magenta', 'Magenta'), ('maroon', 'Maroon'), ('olive', 'Olive'), ('lime', 'Lime'), ('ruby', 'Ruby')], max_length=100)),
                ('price', models.FloatField()),
                ('gender', models.CharField(choices=[('female', 'Female'), ('male', 'Male')], max_length=20)),
                ('rating', models.DecimalField(blank=True, choices=[(0.0, '0'), (1.0, '1 Star'), (2.0, '2 Stars'), (3.0, '3 Stars'), (4.0, '4 Stars'), (5.0, '5 Stars')], decimal_places=1, max_digits=2, null=True)),
                ('by_count', models.IntegerField(default=0)),
                ('sale_count', models.IntegerField(default=0)),
                ('discount', models.FloatField(default=0)),
                ('season', models.CharField(choices=[('summer', 'Summer'), ('winter', 'Winter'), ('spring', 'Spring'), ('Autumn', 'Autumn')], max_length=100)),
                ('category', models.CharField(blank=True, choices=[('Formal', 'Formal'), ('Casual', 'Casual'), ('Sportswear', 'Sportswear'), ('Business', 'Business'), ('Evening', 'Evening'), ('Traditional', 'Traditional')], max_length=100, null=True)),
                ('name', models.CharField(choices=[('oxford', 'Oxford'), ('derby', 'Derby'), ('sandals', 'Sandals'), ('chukka_boots ', 'Chukka Boots '), ('sneakers', 'Sneakers'), ('mules', 'Mules'), ('pumps', 'Pumps'), ('stilettos', 'Stilettos'), ('ballet_flats', 'Ballet Flats'), ('wedges', 'Wedges'), ('mules', 'Mules'), ('ankle_boots', 'Ankle Boots')], max_length=100)),
                ('size', models.IntegerField(choices=[(20, 20), (21, 21), (22, 22), (23, 23), (24, 24), (25, 25), (26, 26), (27, 27), (28, 28), (29, 29), (30, 30), (31, 31), (32, 32), (33, 33), (34, 34), (35, 35), (36, 36), (37, 37), (38, 38), (39, 39), (40, 40), (41, 41), (42, 42), (43, 43), (44, 44), (45, 45), (46, 46), (47, 47), (48, 48), (49, 49), (50, 50)])),
                ('image', models.ImageField(upload_to='shoes_images/')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
